# Generated by Django 2.0.5 on 2020-04-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulka', '0004_auto_20200328_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
